### PR TITLE
Backport Commit 4852e43cb6 to 1.8.x

### PR DESCRIPTION
**Pull request by ksolo**
Updating Nokogiri 1.8.x to utilize the server side includes patch.

### CODE REVIEW

**Comment by tenderlove** [comment]
Huh.  Was the build already red? cc @flavorjones

**Comment by ksolo** [comment]
@tenderlove The patches are not applying correctly. I'll take a deeper look at it.

**Comment by ksolo** [comment]
@tenderlove I did not update the patch number, in the stand alone PR it was patch 0003, in the back port a 0003 already existed and it was applying this before patch 0004 (which is in the same file) causing a diff on line numbers when applying 0004. 

Updated the new patch to be 0005 seem to fix the issue.

**Comment by flavorjones** [comment]
@tenderlove  Is the intention behind this for us to cut a v1.8.6 release, or simply to have this code in the repo and green in CI?

**Comment by ksolo** [comment]
@flavorjones This was failing earlier, what changes were needed to make it pass? Is there a step I was missing when creating the back port?

**Comment by flavorjones** [comment]
The failure was a false valgrind positive -- ruby 2.5 and 2.6 have been doing this a lot :-(

So I just kicked CI and it ran again and it's green.

**Comment by ksolo** [comment]
@flavorjones I can leave this PR open if you think this back port is helpful, otherwise we can close it without merging. If you merge it, I do not have a strong opinion on version bump (1.8.6 over 1.8.5.x)

The application that caused us to make these changes can now work with nokogiri 1.10.x. I'll open a PR for a 1.10.2 version bump.

**Comment by flavorjones** [comment]
@ksolo can we please chat in realtime on IRC or something? #nokogiri on freenode or https://gitter.im/sparklemotion/nokogiri would be great.

**Comment by ksolo** [comment]
@flavorjones I'll send you a message on gitter

**Comment by flavorjones** [comment]
OK - closing the loop here after a chat with @ksolo , I'll try to cut a 1.10.x release later this week with the libxml2 patch; but won't be cutting a 1.8.x patch release.

@ksolo - Thanks for jumping on chat!

**Pull request closed without merging**
