### PR TITLE
Update jing.jar to latest from jing-trang project

### PR DESCRIPTION
**Pull request by henrik-ryom**
The current jing.jar is outdated, and blocks for using a newer outside nokogiri.

### CODE REVIEW

**Comment by flavorjones** [comment]
@henrik-ryom Can you help me understand why you closed this?

**Comment by henrik-ryom** [comment]
Because I wasn't shure this solved my problem.

**Comment by henrik-ryom** [comment]
And I made too many tryouts on my branch

**Comment by henrik-ryom** [comment]
If we stick to my first commit, I think this is mergeable.

**Comment by flavorjones** [comment]
Hi @henrik-ryom -- I took a look, and the jing.jar file in this PR does not match the `jing-20091111.zip` file I downloaded from https://code.google.com/archive/p/jing-trang/downloads

Checking sha-256 checksums, this PR shows:

```
0054b0dcc9ccc4cc33c84c8f6df4093efbec4bd9012a9999433de04fc4a57fa4  lib/jing.jar
```

and the one I downloaded from 20091111 is

```
fe02d596d2f3b1d433efd0a0fac32b7177627d74f6b9127bb5386e88e07282ba  tmp/jing.jar
```

Can you help me understand where you got this file from?

**Pull request closed without merging**
