### PR TITLE
[RFC] Fix #391

### LINKED ISSUE #391: Nokogiri adds 'default' Namespace to elements
I have a situation where I'm using nokogiri to do the following:

1. Extract some nodes from a generated xml file
2. Put extracted nodes into a simple template file
3. Save the template file out as a new file

# My Ruby code

    require 'nokogiri'
    
    input = "input.wxs"
    template = "template.wxs"
    output = "output.wxs"
    
    input_file = Nokogiri::XML(File.open(input))
    template_file = Nokogiri::XML(File.open(template))
    
    #get stuff from input file 
    stuff = input_file.at_css("Directory[Id='TARGETDIR']")
    
    #where to insert in template file 
    insert_point = template_file.at_css("DirectoryRef[Id='InstallDir']")
    
    insert_point.children= stuff.children()
    
    #write out filled template to output file
    File.open(output, 'w') { |f| template_file.write_xml_to f }

# input file

    <?xml version="1.0" encoding="utf-8"?>
    <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
        <Product>
            <Package />
            <Directory Id="TARGETDIR" Name="SourceDir">
                <Component>
                    <File />
                </Component>
            </Directory>
        </Product>
    </Wix>

# template file

    <?xml version="1.0" encoding="utf-8"?>
    <Wix xmlns='http://schemas.microsoft.com/wix/2006/wi'>
      <Fragment Id='MSIComponents'>
          <DirectoryRef Id='InstallDir'>
          </DirectoryRef>
      </Fragment>
    </Wix>

# Actual Output

    <?xml version="1.0" encoding="utf-8"?>
    <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
      <Fragment Id="MSIComponents">
          <DirectoryRef Id="InstallDir">
                <default:Component>
                    <File/>
                </default:Component>
            </DirectoryRef>
      </Fragment>
    </Wix>

### Expected output 

    <?xml version="1.0" encoding="utf-8"?>
    <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
      <Fragment Id="MSIComponents">
          <DirectoryRef Id="InstallDir">
                <Component>
                    <File/>
                </Component>
            </DirectoryRef>
      </Fragment>
    </Wix>

### Nokogiri -v

warnings: []

nokogiri: 1.4.4.1
ruby:
  version: 1.9.2
  platform: i386-mingw32
  engine: ruby
libxml:
  binding: extension
  compiled: 2.7.7
  loaded: 2.7.7

### PR DESCRIPTION
**Pull request by ylecuyer**
This PR fixes #391

### CODE REVIEW

**Comment by flavorjones** [comment]
Hi, @ylecuyer. Thanks so much for the PR!

The test looks reasonable to me, but this change was only made to the C extension, which is now causing JRuby failures. Were you planning on tackling the Java extension, or would you like someone else to look into it?

**Comment by ylecuyer** [comment]
@flavorjones the failure is only due to the test case, it would be nice if someone could help me to improve the test. Currently I'm just comparing the two xml but jruby seems to order the xml nodes in a different way.

**Comment by flavorjones** [comment]
Ah, please ignore my comment above -- this bug doesn't exist on JRuby, and therefore no need to fix it there. :-\

**Comment by flavorjones** [comment]
I've replaced the test in this PR with the test case provided at #391, which avoids the JRuby document output issue in this test. Also cleaned it up a bit, but your name is still on it as author.

Thank you!

**Pull request closed without merging**
