### PR TITLE
Introduce a GitHub Issues template

### PR DESCRIPTION
**Pull request by seanpdoyle**
https://github.com/sparklemotion/nokogiri/issues/1504#issuecomment-231713864

In @flavorjones response to #1504, he describes the proper way to open a
Nokogiri installation issue.

In an effort to improve the quality of issues opened against the
repository, this commit introduces a [GitHub Issue Template][blog].

[blog]: https://github.com/blog/2111-issue-and-pull-request-templates

### CODE REVIEW

**Comment by flavorjones** [comment]
@seanpdoyle Thanks so much for sending this. I'd like to tweak it, but generally this is great. It's been on my "to-do" list for far too long.

**Comment by seanpdoyle** [comment]
@flavorjones I know that this template only addresses installation issues, but I thought it would be a good place to start.

Are there other questions we should be asking issue creators?

Are any of the questions asked not valuable enough to include in the template?

> if you're OSX then we'll need to know more about xcode and will need to see your logs.

How would you phrase this prompt?

**Comment by seanpdoyle** [comment]
Thank you, @flavorjones.

**Comment by flavorjones** [comment]
Merging. Thanks again!

**Pull request merged**
