### PR TITLE
push parser shouldn't throw a NPE when it receives no input

### LINKED ISSUE #1710: NullPointerException in XmlSaxPushParser#native_write triggered by fix for #1261
The last remaining 15 [Blather](https://github.com/adhearsion/blather) test failures are caused @yokolet's fix for #1261 in sparklemotion/nokogiri@3b121ca6e651f513922f9857ba2b4af9d176afb9. I'm not sure exactly what triggers it but sometimes `parserTask.parser.getNokogiriHandler()` returns `null`, leading to a NullPointerException.

Reverting the change allows all the Blather tests to pass. So does skipping the `try` block if the handler is `null`. Strangely changing `SAXException` to just `Exception` in the `catch` clause also makes it work. I'm not sure what the correct fix would be, though presumably reverting the change isn't the way to go.

### PR DESCRIPTION
**Pull request by jvshahid**
fixes #1710

### CODE REVIEW

**Comment by chewi** [comment]
Tested against Blather, all good.

**Comment by chewi** [comment]
Sorry for the ping but I would like to update beyond 1.6 this side of our PCI-DSS audit.

**Comment by flavorjones** [comment]
I'm going to vote for merging this, but would like to file a bug report to get MRI implementation in line with this JRuby behavior (if possible / feasible). @jvshahid if you agree, please merge this and I can cut a release in the next few days.

**Comment by jvshahid** [comment]
merged and opened https://github.com/sparklemotion/nokogiri/issues/1758 to address the inconsistencies between MRI and JRuby

**Pull request merged**
