### PR TITLE
Update Windows cross build for ruby-2.6

### LINKED ISSUE #1842: ruby 2.6 support
Placeholder story to cut a release supporting Ruby 2.6.

Some prior tickets to look at to make sure we're doing everything right:

* https://github.com/sparklemotion/nokogiri/issues/1256
* https://github.com/sparklemotion/nokogiri/issues/1618
* https://github.com/sparklemotion/nokogiri/issues/1706
* https://github.com/sparklemotion/nokogiri/issues/1709

We'll need to:

* [x] add 2.6 to the Windows gem
* [x] update Concourse pipelines to promote 2.6 to main pipeline (see https://github.com/flavorjones/concourse-gem/commit/5c1d1f2510c07339a96fd71b69e1681d0767a2f4)

See also https://github.com/sparklemotion/nokogiri/issues/1841 which discusses removing 2.2. To avoid having an overly-fat binary Windows gem, let's considering doing both in one fell swoop.

### PR DESCRIPTION
**Pull request by larskanis**
This also adds a JRuby task which makes use of new JRuby support in rake-compiler-dock-0.7.0. I'm not sure whether this is something for [build_all](https://github.com/sparklemotion/nokogiri/blob/master/build_all).

Fixes #1842 .

### CODE REVIEW

**Comment by flavorjones** [comment]
... And I've updated `build_all` to use the new task. Thanks again!

**Comment by flavorjones** [comment]
@larskanis I've just cut v1.10.0.rc1, could you please make sure the windows gems look OK to you?

**Comment by larskanis** [comment]
@flavorjones Looks good to me. I tested v1.10.0.rc1 on Windows server 2016:
* binary gems on ruby-2.4-i386 and ruby-2.6-x64 running the nokogiri test suite from github
* `rake compile test` on github master branch on ruby-2.4-i386 and ruby-2.6-x64
* `gem inst --pre --platform ruby nokogiri` and run tests on ruby-2.6.0

Everthing succeeded. `rake compile` on ruby-2.6 emitted a lot of warnings kind of:
* `warning: cast discards 'const' qualifier from pointer target type`
* `warning: Please include winsock2.h before windows.h`
They aren't new and I believe the latter one is a ruby issue.

**Comment by flavorjones** [comment]
Awesome, thank you for performing those tests!

Yes, the compilation warnings have been around for a while and aren't new with 2.6. I've tried squashing them but couldn't find a way to do it without introducing `#pragma`s all over.

**Pull request merged**
