### PR TITLE
Update html5 tests

### PR DESCRIPTION
**Pull request by stevecheckoway**
**What problem is this PR intended to solve?**

html5lib-tests has updated since I forked it to fix a bunch of errors. Some of the updates include new tests to test functionality that changed in the spec. This updates the code to parse the new tests, updates the submodule to include my fixes to the latest version of html5lib-tests, and updates the gumbo parser to accommodate the spec changes.

The new tests were mentioned in https://github.com/sparklemotion/nokogiri/issues/2204#issuecomment-863550189.

**Have you included adequate test coverage?**

Yes. The changes to the parser include parser-specific tests and the update to html5lib-tests includes end-to-end tests to test the behavior.

**Does this change affect the behavior of either the C or the Java implementations?**

This only affects the C implementation as the gumbo parser isn't use for the Java implementation.

### CODE REVIEW

**Comment by stevecheckoway** [comment]
@craigbarnes You'll probably want the changes to gumbo in this PR. The spec changed in its handling of some misformed HTML.

**Comment by flavorjones** [comment]
@stevecheckoway Just as an FYI in case it ended up being not-obvious, here are the gumbo-related test runs for this PR:

- gumbo (linux): https://github.com/sparklemotion/nokogiri/runs/2922756048?check_suite_focus=true
- gumbo (macos): https://github.com/sparklemotion/nokogiri/runs/2922756061?check_suite_focus=true
- gumbo (windows): https://github.com/sparklemotion/nokogiri/runs/2922756054?check_suite_focus=true

And the html5lib tests run in every CI job (see https://github.com/sparklemotion/nokogiri/blob/5e65d56ba49e938b422bf048243ed34460dcc993/.github/workflows/ci.yml#L84-L86 for an example of where we make sure the submodule is checked out, and https://github.com/sparklemotion/nokogiri/runs/2922760696?check_suite_focus=true for an example of the 50,000+ assertions running!).

Everything is green! Go ahead and hit that merge button when you're ready.

**Review by flavorjones — APPROVED** [review]

**Comment by stevecheckoway** [comment]
I don't believe I have access to merge.

**Comment by craigbarnes** [comment]
@stevecheckoway Thanks for the heads up!

**Pull request merged**
