### PR TITLE
ext: ruby 3.3 support

### PR DESCRIPTION
**Pull request by flavorjones**
**What problem is this PR intended to solve?**

Add precompiled native support for Ruby 3.3.

Note that this is still experimental! It is precompiling using a rake-compiler-dock prerelease that uses 3.3.0-preview3.

**Have you included adequate test coverage?**

Testing against 3.3.0-preview3 or head

**Does this change affect the behavior of either the C or the Java implementations?**

N/A

### CODE REVIEW

**Comment by flavorjones** [comment]
I've updated this branch to use rake-compiler-dock v1.4.0.rc1

**Comment by flavorjones** [comment]
Please note this won't get released until one of two things happens:

- the Ruby Core team freezes the ABI (binary interface) for Ruby 3.3 (see https://bugs.ruby-lang.org/issues/19980)
- Ruby 3.3.0 final release arrives

**Comment by agrobbin** [comment]
@flavorjones looks like with the [release of 3.3 RC1 this morning](https://www.ruby-lang.org/en/news/2023/12/11/ruby-3-3-0-rc1-released/), the ABI was frozen!

> After the release of RC1, we will avoid introducing ABI incompatibilities wherever possible. If we need to do, we’ll announce it in the release note.

With that, the corresponding [issue](https://bugs.ruby-lang.org/issues/19980) you linked above has been closed.

**Comment by agrobbin** [comment]
Thanks @flavorjones!!

**Pull request merged**
