### PR TITLE
Download libxml2 and libxslt via HTTP

### PR DESCRIPTION
**Pull request by eagletmt**

### CODE REVIEW

**Comment by flavorjones** [comment]
Thank you for this contribution!

I would like to understand why you're suggesting this change. Can you explain why you think this is necessary or better?

**Comment by eagletmt** [comment]
There's an environment where the network is somewhat restricted because of nat, proxy, etc.
Since FTP is less comon than HTTP nowadays, only HTTP(S) works correctly in such an environment.
It would be better to me if I can download the tarball via HTTP.

**Comment by flavorjones** [comment]
Thanks again!

**Comment by eagletmt** [comment]
Thank you!

**Comment by eagletmt** [comment]
Are there any plan to release a new version?
I'm suffering from this issue.

**Pull request merged**
