### PR TITLE
Fix: code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
#### Description
This PR fixes a few issues that were affecting the code quality.

#### Summary of changes

- Prefer rescuing `StandardError` over `Exception`
- Remove unused variable assignments
- Prefer initializing with literal over a method that results in literal
- Enclose command literals in backticks
- Omit pipes for the empty block parameters
- Remove redundant and unnecessary require statement
- Use `__dir__` to get an absolute path

### CODE REVIEW

**Comment by flavorjones** [comment]
When you say "code quality issues", can you help me understand what problem you're trying to solve?

**Comment by withshubh** [comment]
> When you say "code quality issues", can you help me understand what problem you're trying to solve?

@flavorjones :wave: 

Most of the issues which I have fixed were potential bug risks or the anti-patterns in code.

**Comment by flavorjones** [comment]
I appreciate that you're trying to help. However, most of these changes are stylistic and not substantive, and I'd prefer not to merge changes like this (similar to the Rails project policy).

As a side note, reading these changes framed as "code quality issues" caused an emotional response that I had to work to get past. I'd encourage you to be sensitive to how maintainers might read a contribution like this, and suggest you simply say "formatting and style improvements" which is a less judgemental phrase.

Also, in case you didn't notice: these changes cause test failures which you can see in the checks section above or by running the tests locally on your machine.

If you're interested in contributing to Nokogiri can I suggest you take a look at the "help wanted" label?

https://github.com/sparklemotion/nokogiri/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

**Comment by withshubh** [comment]
> As a side note, reading these changes framed as "code quality issues" caused an emotional response that I had to work to get past. I'd encourage you to be sensitive to how maintainers might read a contribution like this, and suggest you simply say "formatting and style improvements" which is a less judgemental phrase.

Apology and Noted! :sparkles: 


> Also, in case you didn't notice: these changes cause test failures which you can see in the checks section above or by running the tests locally on your machine.

I was working on fixing the tests.

**Pull request closed without merging**
