### PR TITLE
[DOC] Doc for XML::ParseOptions

### PR DESCRIPTION
**Pull request by BurdetteLamar**
Revises the documentation for `XML::ParseOptions`.

### CODE REVIEW

**Comment by flavorjones** [comment]
Thank you for taking the time to improve these docs! I'll make some time to do fact-checking but after a quick pass this is a huge improvement. ♥

**Comment by BurdetteLamar** [comment]
Couple of things.
At first I had a table, and so used GHFM table (and therefore markdown instead of rdoc format).  Will change back to rdoc if you like.
I've omitted remarks about which options are defaults for which methods, thinking that the best place to do that is in the methods' own docs.  Those call-seqs need adjustments about options defaults;  should those be in this PR (or can they wait)?

    On Friday, November 29, 2024 at 08:56:23 AM CST, Mike Dalessio ***@***.***> wrote:  
 
 


Thank you for taking the time to improve these docs! I'll make some time to do fact-checking but after a quick pass this looks like a huge improvement. ♥

**Comment by BurdetteLamar** [comment]
@flavorjones, I'd like to close this and put up a revision of this later on.  I've also been working on a new page (`doc/parsing.md`);  both of these efforts will profit greatly from the `kwargs` improvements that are in progress.  It would serve us all better for me to work on the `kwargs` now, and the other stuff after.

**Comment by flavorjones** [comment]
@BurdetteLamar OK! Also please see #3355 which is where a great deal of documentation has been updated for the keyword arguments.

**Comment by flavorjones** [comment]
@BurdetteLamar Hoping to release v1.17.0 today.

**Comment by BurdetteLamar** [comment]
> @BurdetteLamar Hoping to release v1.17.0 today.

@flavorjones Outstanding!

**Pull request closed without merging**
