### PR TITLE
jruby improvements + weaker xpath caching

### LINKED ISSUE #1281: RuntimeError when calling to_s with jruby
Hello 
using Jruby with some html tags (Nokogiri xml elements) I get this error which crashes the program
the error doesnt always occur, so it is hard to provide a sample code, but it looks like

``` ruby
doc.css('meta').each do |t|
  puts t
  a << t.to_s
end
```

I think it might have to do with invalid encodings, but it's just a guess.
Is there a woraround for this?

``` code

RuntimeError: Input length = 1
  native_write_to at nokogiri/XmlNode.java:1217
         write_to at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:686
        serialize at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:618
        to_format at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:774
          to_html at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:630
             to_s at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:501
    get_meta_tags at /home/binaryplease/committance/crawler2/crawler/crawler.rb:147
             each at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node_set.rb:187
             upto at org/jruby/RubyInteger.java:133
             each at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node_set.rb:186
    get_meta_tags at /home/binaryplease/committance/crawler2/crawler/crawler.rb:146
  fetch_page_tags at /home/binaryplease/committance/crawler2/crawler/crawler.rb:213
             each at org/jruby/RubyArray.java:1613
  fetch_page_tags at /home/binaryplease/committance/crawler2/crawler/crawler.rb:205
     get_contents at /home/binaryplease/committance/crawler2/crawler/crawler.rb:117
     process_link at /home/binaryplease/committance/crawler2/crawler/worker.rb:104
     process_link at /home/binaryplease/committance/crawler2/crawler/worker.rb:114
             each at org/jruby/RubyArray.java:1613
     process_link at /home/binaryplease/committance/crawler2/crawler/worker.rb:114
            start at /home/binaryplease/committance/crawler2/crawler/worker.rb:74
             each at org/jruby/RubyArray.java:1613
            start at /home/binaryplease/committance/crawler2/crawler/worker.rb:74
            start at /home/binaryplease/committance/crawler2/crawler/worker.rb:58
    process_batch at /home/binaryplease/committance/crawler2/crawler/crawler_client2.rb:120
             call at org/jruby/RubyProc.java:271
       initialize at /home/binaryplease/committance/crawler2/crawler/thread_pool.rb:14
             loop at org/jruby/RubyKernel.java:1507
       initialize at /home/binaryplease/committance/crawler2/crawler/thread_pool.rb:12
            catch at org/jruby/RubyKernel.java:1270
       initialize at /home/binaryplease/committance/crawler2/crawler/thread_pool.rb:11
```

### LINKED ISSUE #1595: xpath function returning an int fails under jruby
e.g. `xml.xpath('nokogiri:anint()', @ns, @handler)` (where `@handler#anint` returns a Fixnum)

### PR DESCRIPTION
**Pull request by kares**
managed to run into more common problems such as cloning non-cloneable (Java) objects.
a bit ugly pattern in general but for the rest of Ruby object cloning it would need a justification.

further I realized some xpath problems : 
- using a Ruby function which returns an `Integer` was not supported (resolved #1595) 
- xpath-context caching would not work for xpath-s using binds or a custom fn-handler

this is now avoided (such expressions always create a new xpath context) - they are less common. 
`xpath(expr)` still caches as before, but I realized the cache makes `xpath()` not thread-safe #1596 

UPDATE: also added a fix for #1440 (also resolves #1281 which is a duplicate - had the same cause)

### CODE REVIEW

**Comment by flavorjones** [comment]
Thank you for submitting this, @kares!

Can you please rebase this off current master? It doesn't have 92768e0 in it, so the CI pipeline is failing when testing against libxml system libraries. See https://ci.nokogiri.org/teams/nokogiri-core/pipelines/nokogiri/jobs/ruby-2.4-system-pr/builds/3 for specifics.

**Comment by kares** [comment]
rebased and all :green_heart: now ... thanks for the feedback. 
hoping this will also get into 1.7.1 but take your time if you need to reviewing this.

numbers show that doc parsing is ~ 10% faster + xpath has gone 2x faster in some of the cases I tested.

**Comment by flavorjones** [comment]
Yep, about to merge! Just writing CHANGELOG entries now.

Thanks so much!

**Comment by flavorjones** [comment]
Merged manually.

thumbs-up-simon-pegg

**Pull request closed without merging**
