### PR TITLE
Using symbol to proc

### PR DESCRIPTION
**Pull request by bruno-**
This pull request contains simple mechanic changes from using blocks to symbol
to proc.

### CODE REVIEW

**Comment by larskanis** [comment]
I don't have a strong opinion to this, but it's surely a bit more readable.
@sparklemotion/nokogiri-core Any objections to merge this?

**Comment by knu** [comment]
Actually, since a proc made from a symbol does not (need to) capture the environment, the symbol to proc style `map(&:foo)` will run faster than the closure style.

**Comment by knu** [comment]
By the way, do we have coverage numbers to make sure the lines touched are all covered by the test suite?

**Comment by larskanis** [comment]
> By the way, do we have coverage numbers to make sure the lines touched are all covered by the test suite?

Good point - will check this.

**Comment by larskanis** [comment]
@knu  We have a very good coverage. In fact all the changes of this PR are covered.

**Comment by larskanis** [comment]
@bruno- Merged, thank you!

**Pull request merged**
