### PR TITLE
Fix for #843

### PR DESCRIPTION
**Pull request by codekitchen**
I took https://github.com/sparklemotion/nokogiri/pull/1058 and fixed the Java implementation so that the tests pass.

Without these fixes, the test crashes on MRI (failed assert) and fails in JRuby.

### CODE REVIEW

**Comment by codekitchen** [comment]
Hm I'm not familiar with appveyor, but that failure `Specify a project or solution file. The directory does not contain a project or solution file.` seems out of my hands. Perhaps I caught nokogiri in a transition?

**Comment by larskanis** [comment]
@codekitchen  Don't worry about appveyor, it is currently broken. PR https://github.com/sparklemotion/nokogiri/pull/1310 fixes that, among others issues.

**Comment by codekitchen** [comment]
good to know, thanks @larskanis

**Comment by flavorjones** [comment]
Tentatively targetting 1.6.8 for this.

**Pull request closed without merging**
