### PR TITLE
Fix XML::Builder not handling exceptions safely - 2372

### PR DESCRIPTION
**Pull request by ric2b**
**What problem is this PR intended to solve?**

https://github.com/sparklemotion/nokogiri/issues/2372

**Have you included adequate test coverage?**

I think so.

**Does this change affect the behavior of either the C or the Java implementations?**

Yes, since this changes non-platform specific code.

Co-authored-by: Joana Tavares <jtavares@salsify.com>

### CODE REVIEW

**Review by flavorjones — APPROVED** [review]
LGTM, thanks so much for taking the time to do this.

**Comment by flavorjones** [comment]
I'll wait for CI to go green before merging.

**Comment by flavorjones** [comment]
Please ignore the Windows Ruby 2.5 failures - they're unrelated and I'm investigating at https://github.com/sparklemotion/nokogiri/issues/2354

**Comment by flavorjones** [comment]
I've added a commit to this PR that updates the CHANGELOG with a thank-you to both @ric2b and @rinthedev

**Comment by ric2b** [comment]
Thanks for looking at it so quickly! :)

**Comment by flavorjones** [comment]
Merged! Will ship in the next release (not sure yet whether that will be 1.12.6 or 1.13.0)

**Pull request merged**
