### PR TITLE
Add fat binary gem support for ruby-3.1

### LINKED ISSUE #2397: Ship Ruby 3.1 precompiled native support
This is a placeholder to ship a new version of Nokogiri with Ruby 3.1 precompiled native support.

Please note that **Nokogiri supports Ruby 3.1**, but until a precompiled native gem is shipped, you will have to use the `ruby` vanilla platform gem which will compile from source during installation. Modern `bundler` will do this for you automatically.

This work is currently waiting for a version of rake-compiler-dock with Ruby 3.1 build capabilities. The maintainers of that project are aware, and there is no need to bother them. Feel free to subscribe to this issue and I'll keep it updated.

See #2408 for status.

### PR DESCRIPTION
**Pull request by larskanis**
Ruby-3.1-x64 on Windows has a changed platform string "x64-mingw-ucrt" vc. "x64-mingw32".
Consequentally rake-compiler-dock has a new corresponding platform image.
See https://rubyinstaller.org/2021/12/31/rubyinstaller-3.1.0-1-released.html

Unfortunately the compiler triplet is still "x86_64-w64-mingw32" for both ruby platforms, although the compiled code isn't compatible.
Therefore we have to differ by RUBY_PLATFROM instead of the "host" string.

**What problem is this PR intended to solve?**

It shall add binary gems for ruby-3.1.

**Have you included adequate test coverage?**

This is another PR https://github.com/sparklemotion/nokogiri/pull/2408

**Does this change affect the behavior of either the C or the Java implementations?**

C only.

Fixes #2397

### CODE REVIEW

**Comment by flavorjones** [comment]
@larskanis Thanks so much for shipping this. I'm going to merge #2408 and rebase this on top of it.

**Comment by larskanis** [comment]
Oh, I just noticed that arm64-darwin doesn't build. I'll update the PR.

**Comment by flavorjones** [comment]
@lars Can you please peek at 0c3274960a1c71af0729c83c5dd3f8b1fd6dd5b7 and tell me if that Windows ucrt test for the native gem looks right?

**Comment by flavorjones** [comment]
@larskanis Not sure if you're actively working on this, I don't want to clobber any work you're doing ...

I think we need to change the "host" values being used, since that string is used to prefix toolchain commands in the build container (e.g., "ar"). Specifically, "x86_64-linux-gnu-ar" doesn't exist, and I think that host should be "x86_64-linux" (without the "gnu"). I'm happy to do this, but again don't want to clobber your work in progress. Please let me know if I can proceed with making those changes.

**Comment by flavorjones** [comment]
@larskanis So this change broke some things:

```patch
-    # Prefer host_alias over host in order to use i586-mingw32msvc as
-    # correct compiler prefix for cross build, but use host if not set.
-    recipe.host = RbConfig::CONFIG["host_alias"].empty? ? RbConfig::CONFIG["host"] : RbConfig::CONFIG["host_alias"]
+    recipe.host = RbConfig::CONFIG["host"]
```

An example is how we derive the name of the "ar" tool for building libgumbo.

I'm not familiar with why this particular change was made, and I wish we were collaborating more closely on these changes. Can you help me understand why this change was made and whether I can safely revert it (it seems to work fine when I do)?

**Comment by flavorjones** [comment]
@larskanis I'm going to step away for the evening, but I will have time tomorrow to collaborate -- in real time -- if you're willing and able to. Thanks for working on this!

**Comment by larskanis** [comment]
Tests look good now. I don't understand the JRuby install error. It looks like https://github.com/jruby/jruby/issues/6904 . I tried to use ruby-maven from git, but to no avail.

**Comment by flavorjones** [comment]
Thank you! I have some context on the JRuby thing, I'll take a look this morning.

**Comment by flavorjones** [comment]
@larskanis rake-compiler sets the gemspec `required_ruby_version` to

```ruby
spec.required_ruby_version = [
  ">= #{ruby_api_version(sorted_ruby_versions.first)}",
  "< #{ruby_api_version(sorted_ruby_versions.last).succ}.dev"
]
```

(see https://github.com/rake-compiler/rake-compiler/blob/master/lib/rake/extensiontask.rb#L282-L285)

For Nokogiri this will always be `[">= 2.6", "< 3.2.dev"]`, which is incorrect for the windows gems now. I've patched it up locally in 56b89d9 but I'd like to understand if we should be using rake-compiler differently to make this happen automatically (or if we should add a feature to rake-compiler to do so).

**Pull request merged**
