### PR TITLE
Switch to upstream html5lib-tests

### LINKED ISSUE #2282: Update html5lib-tests test to official repo
Blocked on:

- [x] https://github.com/html5lib/html5lib-tests/pull/136

If the tests end up [moving to the WPT](https://github.com/html5lib/html5lib-tests/issues/127) then we should switch to tracking that instead.

### PR DESCRIPTION
**Pull request by stevecheckoway**
My PR to fix the errors
https://github.com/html5lib/html5lib-tests/pull/136 was merged. We can
now track the upstream repository.

Closes #2282

**What problem is this PR intended to solve?**

The html5 tests had been tracking my fork of html5lib-tests but with https://github.com/html5lib/html5lib-tests/pull/136 merged, we can track upstream. #2282 

**Have you included adequate test coverage?**

There is no change in test coverage.

**Does this change affect the behavior of either the C or the Java implementations?**

This is only relevant to the C implementation, but it affects the behavior of neither.

### CODE REVIEW

**Comment by stevecheckoway** [comment]
I'm not completely sure I correctly updated the submodule. Hopefully the CI run will make it clear which commit from which repo the submodule was checked out.

**Comment by flavorjones** [comment]
@stevecheckoway Would it be useful to have a job in the "upstream" CI pipeline to run tests against the latest head of `html5lib/html5lib-tests`?

That pipeline [runs a few times a week on a timer](https://github.com/sparklemotion/nokogiri/blob/main/.github/workflows/upstream.yml#L18) to give us some advanced notice if upstream changes are causing test failures.

If that seems useful, I'm happy to add the job to this PR or create a separate one, whichever you'd prefer.

**Comment by flavorjones** [comment]
Ah, I'm going to merge this and we can chat about an upstream job in a new PR.

**Comment by stevecheckoway** [comment]
Such an upstream job sounds like a fantastic idea!

**Comment by flavorjones** [comment]
See #2288 for upstream PR.

**Pull request merged**
