### PR TITLE
remove allow_failure jruby-9.0.0.0 from .travis.yml

### PR DESCRIPTION
**Pull request by marutosi**

### CODE REVIEW

**Comment by knu** [comment]
Now what was the reason behind the excludes for osx?

**Comment by knu** [comment]
Hmm, master's got somehow broken, but I have no idea as to why, since the commit should not affect other versions of jruby which failed.

**Comment by flavorjones** [comment]
I'm looking at broken jruby builds on master, don't worry about it for now.

We excluded jrubies on OSX because I don't expect jruby to act differently on different platforms the same way I expect C compilers and extconf to act differently.

We excluded 2.2 on OSX because it wasn't available yet at the time. I'll try adding it back today and see whether Travis supports it.

**Comment by flavorjones** [comment]
Just following up: 2.2 on OSX is working on travis now: https://travis-ci.org/sparklemotion/nokogiri

**Pull request merged**
