### PR TITLE
ci: try UCRT for windows ruby-head builds

### PR DESCRIPTION
**Pull request by flavorjones**
**What problem is this PR intended to solve?**

The 3.1.0.dev windows ruby installer uses UCRT, see #2268 for context. This gives Nokogiri and @larskanis a feedback loop.

### CODE REVIEW

**Comment by flavorjones** [comment]
@larskanis This looks like it might be a genuine failure on UCRT? 

> https://github.com/sparklemotion/nokogiri/runs/2848463493?check_suite_focus=true#step:7:50

**Comment by larskanis** [comment]
The failure happens when calling the XLST function `date:date()`. So the issue resides in libxslt pretty sure. In contrast to MSVCRT, UCRT has non ANSI-C compatible time functions. This already needed a [fix in ffi](https://github.com/ffi/ffi/commit/4924308429dd5535cbd7795ff503315cdddad06a). I guess that libxslt simply disables date+time functions on UCRT. I'll try to fix that.

**Comment by flavorjones** [comment]
@larskanis That's interesting! Looking at `libexslt/date.c` it seems like `HAVE_TIME` is a compile-time macro:

```c
#if defined(HAVE_TIME_H)					\
    && (defined(HAVE_LOCALTIME) || defined(HAVE_LOCALTIME_R))	\
    && (defined(HAVE_GMTIME) || defined(HAVE_GMTIME_R))		\
    && defined(HAVE_TIME)
#define WITH_TIME
#endif
```

I'll also note that it's fine when Nokogiri compiles it (`--disable-system-libraries`), but not when we use the UCRT system libraries (`--enable-system-libraries`), which I don't fully understand.

Anything I can do to help?

**Comment by flavorjones** [comment]
Also: I'd be fine with not fixing this. For example, when using a version of libxml2 that does not have iconv support compiled in, we skip the tests and expose that configuration as part of VERSION_INFO.

**Comment by flavorjones** [comment]
WDYT of the following solution:

- during Nokogiri initialization, call `exsltDateDate(NULL)`
- if the return value is NULL, set a ruby constant like `NOKOGIRI_LIBXSLT_TIME_SUPPORT` to false
- else set it to true
- expose it in `VERSION_INFO`

Then we can either rewrite the failing test to not depend on date/time functionality, and/or conditionally run tests based on the value of the constant.

**Comment by larskanis** [comment]
I opened a PR on Mingw-packages addressing the date/time issue: https://github.com/msys2/MINGW-packages/pull/8957

**Comment by flavorjones** [comment]
@larskanis In the meantime, I have a commit on this PR to detect whether libxslt is built with date-time functionality, and skip the assertion if not.

**Comment by larskanis** [comment]
The latest MSYS2 package `mingw-w64-ucrt-x86_64-libxslt-1.1.34-4` is now in the official repository and it fixes the date/time issue on UCRT64.

**Comment by flavorjones** [comment]
@larskanis yup! looks good in this build: https://github.com/sparklemotion/nokogiri/runs/2873137424?check_suite_focus=true#step:7:35

**Comment by OMERKHALIDFATHIFATHI** [comment]
وت

**Pull request merged**
