### PR TITLE
HTML5 documents should not require namespaces in CSS selector queries

### PR DESCRIPTION
**Pull request by flavorjones**
**What problem is this PR intended to solve?**

Discussion at #2376 led to the decision to continue to parse HTML5 foreign elements with namespaces, but not to require that namespace in CSS queries.

So, in the canonical example:

```html
<!DOCTYPE html>
<html>
  <body>
    <div id="svg-container">
      <svg version="1.1" width="300" height="200" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="red" />
        <circle cx="150" cy="100" r="80" fill="green" />
        <text x="150" y="125" font-size="60" text-anchor="middle" fill="white">SVG</text>
      </svg>
    </div>
  </body>
</html>
```

Nokogiri will respond to the following searches:

```ruby
doc.css("svg") # ⇒ returns the svg element
doc.css("nsfoo|svg", { "nsfoo" => "http://www.w3.org/2000/svg" }) # ⇒ also returns the svg element
```

In order to accomplish this, this PR is rather invasive, but leaves a lot of code better factored, better documented, more flexible, and more extensible.

Specific changes:

- `Nokogiri::CSS.xpath_for` allows a `Nokogiri::CSS::XPathVisitor` to be injected for fine-grained control over how CSS selectors are translated into XPath queries
- the CSS cache is extended to account for XPathVisitor configuration
- patch libxml2 to support wildcard namespaces in XPath queries (nonstandard in XPath 1.0)
- `HTML5` documents and fragments translate child-axis searches into a wildcard-namespace query if libxml2 is patched; else use a builtin xpath function if libxml2; else use standard XPath local-name() (this order of preference reflects performance, faster-is-more-preferred)

**Have you included adequate test coverage?**

Oh yesssss.

Also here are the benchmarks of the various implementations:

```text
      //span
           18.923k (± 8.9%) i/s -     93.906k in   5.010792s
      //*[local-name()='span']
            1.849k (± 2.8%) i/s -      9.261k in   5.011560s
      //*[nokogiri-builtin:local-name-is('span')]
            3.191k (± 2.4%) i/s -     16.150k in   5.064798s
      //*:span
           18.016k (± 4.6%) i/s -     89.900k in   5.003444s
    
      Comparison:
      //span:
          18922.5 i/s
      //*:span:
          18016.5 i/s - same-ish: difference falls within error
      //*[nokogiri-builtin:local-name-is('span')]:
           3190.6 i/s - 5.93x  (± 0.00) slower
      //*[local-name()='span']:
           1849.4 i/s - 10.23x  (± 0.00) slower
```

I'll also drop in some graphs of the callstacks below.

**Does this change affect the behavior of either the C or the Java implementations?**

HTML5 is already only supported by CRuby, and so much of this functionality is simply not going to be turned on in JRuby. That said, if we need this functionality in JRuby, the fallback use of standard XPath `local-name()` would suffice until a need arose for performance optimizations there.

### CODE REVIEW

**Comment by flavorjones** [comment]
Callstacks! You'll notice that the queries that use xpath functions end up spending a lot of time in the xpath function stack, and in allocating memory for the objects on that "stack" including the short-lived return values. The standard query and the wildcard query are faster because the comparisons are being done "inline" in the XPath query engine, without invoking xpath functions.


Callstack for standard child-axis query:
element-name

Callstack for local-name query:
local-name

Callstack for the builtin function query:
builtin

Callstack for the wildcard namespace query:
wildcard

**Comment by flavorjones** [comment]
I could use a review in particular of the libxml2 patch https://github.com/sparklemotion/nokogiri/pull/2403/commits/b52dde7ddbe3b6dcc5a6dd6219160ef7b71f9014, because this feels a little bit risky.

Worth noting, though: with that patch applied, libxml2's full test suite still passes.

**Comment by stevecheckoway** [comment]
I spent a little while looking at the xpath.c patch. Nothing jumps out at me as being wrong, but the file is huge and it's difficult to know what the implications are precisely. I'll try to look more closely this coming week.

**Comment by flavorjones** [comment]
@stevecheckoway Thanks for the spot check. I'm going to merge this and accept a little bit of risk, because both libxml2 and nokogiri's full test suites still pass with that libxml2 patch applied.

**Comment by stevecheckoway** [comment]
I think that makes sense. Sorry for not doing a better review in a reasonable amount of time.

**Comment by flavorjones** [comment]
Oh, please don't apologize! I appreciate your attention.

**Pull request merged**
