### PR TITLE
Update changelog and version number

### PR DESCRIPTION
**Pull request by ksolo**
preparing to bump version of nokogiri from 1.10.1 - 1.10.2
* updated changelog with a date
* updated lib/nokogiri/version.rb with new version info

cc/ @tenderlove

### CODE REVIEW

**Comment by flavorjones** [comment]
OK - closing the loop here, I'll try to cut a 1.10.x release later this week with the libxml2 patch; but won't be cutting a 1.8.x patch release.

**Comment by flavorjones** [comment]
Just want to note here that CI failed because that particular step installs the gem and runs tests; because you bumped the version number, the test installed v1.10.1 from rubygems and tests added to master since then failed. This isn't generally how we bump versions and CI is confused.

**Comment by acidphuck** [comment]
I have been trying to install nokogiri on ruby 2.6.1-2 but not succeeded. I m using termux. Can anyone help me?

**Comment by ksolo** [comment]
@acidphuck I can try to help. 

This is a great place to start: https://nokogiri.org/tutorials/installing_nokogiri.html

It may be worth opening up a different issue since this one is going to be closed out soon. In that issue can you add the operating system, along with copying and pasting terminal output for the installation?

**Comment by flavorjones** [comment]
@ksolo I'm going to close this without merging; but will make these changes on master. Thanks again for shepherding the security updates that will go into this next version!

**Pull request closed without merging**
