### PR TITLE
fix JRuby SAX parser entity handling

### PR DESCRIPTION
**Pull request by flavorjones**
**What problem is this PR intended to solve?**

https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-2rr5-8q37-2w7h (may be private for now)

**Have you included adequate test coverage?**

Yes.

**Does this change affect the behavior of either the C or the Java implementations?**

The Java implementation behavior now matches the C implementation behavior.

### CODE REVIEW

**Comment by kovyrin** [comment]
Testing the most recent version of Nokogiri, I am still seeing it resolve at least some external entities. Here is how I'm testing it:

I have the following sitemap XML:

```xml
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE urlset [
      <!ENTITY test SYSTEM "file:////tmp/do-not-visit.txt">
    ]>

    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
      <url>
        <loc>http://127.0.0.1:9393/</loc>
        <lastmod>2019-06-19</lastmod>
        <changefreq>daily</changefreq>
      </url>
      <url>
        <loc>http://127.0.0.1:9393/visit-here</loc>
        <lastmod>2019-06-19</lastmod>
        <changefreq>daily</changefreq>
      </url>
      <url>
        <loc>&test;</loc>
        <lastmod>2019-06-19</lastmod>
        <changefreq>daily</changefreq>
      </url>
    </urlset>
```

The `/tmp/do-not-visit.txt` file contains `http://127.0.0.1:9393/do-not-visit-here`. When I try to parse the sitemap with nokogiri, I'm seeing 3 URLs and one of them is `http://127.0.0.1:9393/do-not-visit-here`, so Nokogiri has read a local file and put its contents into the sitemap.

Let me know if I'm missing something here.

**Comment by flavorjones** [comment]
@kovyrin Please open a new issue with a complete repro script including answering the questions in the bug report template. Thank you!

**Comment by kovyrin** [comment]
Actually, nm, the issue seems to be in a different library we use next to nokogiri specifically for sitemap parsing :-(

**Comment by flavorjones** [comment]
> the issue seems to be in a different library

Phew! Thanks for closing the loop here and letting us know.

**Pull request merged**
