### PR TITLE
wip - migrate to oedipus_lex

### PR DESCRIPTION
**Pull request by flavorjones**
**What problem is this PR intended to solve?**

@zenspider is making the case that oedipus_lex is better, faster, and better supported than rexical. Let's try it (again).

See prior work at https://github.com/sparklemotion/nokogiri/issues/1337

To reproduce [the failing test](https://github.com/sparklemotion/nokogiri/actions/runs/5603609266/jobs/10250688248): run `bundle exec rake css:clean css:generate`

### CODE REVIEW

**Comment by zenspider** [comment]
All greened up. DO NOT MERGE AS IS... I added a `do_parse` method to the tokenizer that is bogus... but makes the tests pass??? Needs to be verified.

**Comment by flavorjones** [comment]
@zenspider Thanks for your work on this. I'm back from vacation and will make time to take a look in the next few days.

**Comment by zenspider** [comment]
no rush!

**Comment by flavorjones** [comment]
I'm going to be moving Nokogiri to a hand-written tokenizer and parser for the CSS selectors. See #2560

**Pull request closed without merging**
