### PR TITLE
Add line column to message

### PR DESCRIPTION
**Pull request by spk**
Useful for `map(&:to_s)` and simple output

### CODE REVIEW

**Comment by flavorjones** [comment]
Oooh, I really like this feature. I may clean it up so that it reads better, but thanks for putting the time and though into this!

**Comment by spk** [comment]
Hi @flavorjones, thanks, don't hesitate to comment I will take the time to fix the issues you will report.

**Comment by flavorjones** [comment]
Looks like this works on rbx-3 without needing to make the change in cbdd787.

**Comment by flavorjones** [comment]
Merged the initial commit of this PR manually.

Thank you for the PR!

**Pull request closed without merging**
