### PR TITLE
Drop support for Ruby 2.3

### LINKED ISSUE #1886: Deprecate Ruby 2.3 support
As noted at https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/ upstream support for Ruby 2.3 ended on March 31, 2019.

This issue is to formally remove Ruby 2.3 support from Nokogiri, including;

* update README and gemspec to indicate this change
* remove Ruby 2.3 from CI pipelines
* remove Ruby 2.3 from windows cross-compiled gem (`.cross_rubies`)

Marking this for a 1.11.0 release to coincide with a minor version bump (not a patchlevel version bump).

### PR DESCRIPTION
**Pull request by ashmaroli**
**What problem is this PR intended to solve?**

Resolves #1886 

**Have you included adequate test coverage?**

*Not required.*

**Does this change affect the C or the Java implementations?**

No, this doesn't.

### CODE REVIEW

**Comment by fulldecent** [comment]
@flavorjones requesting please to add to v1.11.0 at https://github.com/sparklemotion/nokogiri/milestone/18

**Comment by flavorjones** [comment]
Hi - thanks much for submitting this PR. Unfortunately, some of the files you're editing here are automatically generated by the dev dependency `concourse-gem`. I'll take the remaining changes through a manual merge, though.

**Comment by ashmaroli** [comment]
@flavorjones No worries. Feel free to close this PR if that would be easier for you.

**Comment by flavorjones** [comment]
Manually merged after editing the commit to remove the concourse changes, and credited you in the CHANGELOG. Thanks!

**Comment by ashmaroli** [comment]
Thank you for the mention @flavorjones.

**Pull request closed without merging**
