### PR TITLE
Frozen String Literal Compatibility

### PR DESCRIPTION
**Pull request by twalpole**
Turns on frozen string literals in 2.3.0+ and fixes code for it.

### CODE REVIEW

**Comment by flavorjones** [comment]
@larskanis I know you've already put thought and work into frozen strings ... can you comment?

**Comment by twalpole** [comment]
Sorry -- I didn't see @larskanis work towards this.  One thing to note is that I used `String.new("")`  rather than `String.new` for a new empty string.  One would think they would be identical however it turns out the first produces a string with the encoding of the document  - the second has an encoding of ASCII-8BIT for some reason.

**Comment by twalpole** [comment]
@flavorjones The second commit here fixes the random failures that have been occurring on PRs, caused by test order and when the encoding alias added by default was cleared.  If you don't want the frozen literal changes you may want to cherrypick the second commit separately

**Comment by larskanis** [comment]
I don't think we want to pollute all the nokogiri files with this magic comment.

@twalpole The difference between `String.new` and `String.new("")` is because the first one doesn't have a source file context, so it can not get any encoding information. The latter one don't build a string with the encoding of the XML document, but with the encoding of the surrounding source file. However this difference doesn't change the nokogiri-API at all.

IMO we can close this in favor of #1413 .

**Comment by twalpole** [comment]
The "pollution" of the magic comment allows nokogiri to gain the benefits of default frozen literals before every other gem a project (using nokogiri) depends on being updated to allow someone to use the ruby switch.  

Either way - the second part of the commit attempts to fix the random invalid encoding test failures that have been occuring, so might be worth cherrypicking

@larskanis Yes, by document I meant the file it was in, not the XML document - updated comment to clarify, and I would say String.new does have a context (the file it's called in) although I guess the default value passed to it is declared in the source file.  It may not change the Capybara API but it does mean if you then immediately concat to the new string there are encoding translations that need to be made and you end up with a string that is not in the encoding one would generally assume (if just creating a literal)

**Comment by larskanis** [comment]
@twalpole Sorry, I missed the second commit, but cherry-picked it to master, now.

**Comment by flavorjones** [comment]
Closing, frozen string support is now on master.

**Pull request closed without merging**
