### PR TITLE
Start using jar-dependencies in the gemspec.

### PR DESCRIPTION
**Pull request by headius**
This change affects the Java gem and is an attempt to start using Maven artifacts for all the jar dependencies in Nokogiri.

See #1253. The commented versions can't be found on Maven Central. Until we can resolve them, they would have to remain as bare jar files in the repository and gem.

Next step for this PR would be to get the gem building using jar-dependencies and remove the properly-versioned jars from the repository.

### CODE REVIEW

**Comment by jvshahid** [comment]
For future reference, I tried `org.codelibs:nekohtml,` but the latest version `2.1.0` only supports Java version 11 and up.  When I ran the tests against version `2.0.2`, the newest version that supports Java 8, I saw four tests fail.

I also submitted a patch to the Nekohtml project on [sourceforge](https://sourceforge.net/p/nekohtml/patches/24/). I am not sure if that will go anywhere, given that the mailing list hasn't been active in a few years.

**Comment by jvshahid** [comment]
@headius or @mkristian can either one of you help me understand how to use `jar-dependencies` in development?  I tried to check out this branch locally, delete the jars declared in `Rakefile` from `lib/,` and run `bundle exec rake compile.`  I expected the jars to be available on the classpath for the compiler. Instead the java compiler failed because it couldn't find the classes.

**Comment by headius** [comment]
@jvshahid Will have to wait for mkristian...I'm not clear on how to use jar-deps in dev either.

**Comment by mkristian** [comment]
Will make same time this week to integrate jar-dependencies. Will do it in a way it fits with rake work flow. Will ping you guys.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mkristian** [comment]
I have something working but I am unsure what the best/easiest way to manage this.

one way would be to add a rake tasks which updates the jars and otherwise wire up jar-dependencies to use the installed jars.

**Comment by mkristian** [comment]
@headius @jvshahid please see my branch
https://github.com/mkristian/nokogiri/tree/jar-deps

* load all jar via jar-dependencies using it maven coordinate
* add rake task to update jar using Jarfile as source
* using Jarfile to declare jar deps in gemspec

a few jars are not part of maven central so I copies them to right place, i.e. they will be still part of the duplicate jar warning/detection of jar dependencies. the jing.jar will start up but produces NullPointerException in tests. Still need to look into this - as I did see the same errors when using the original jar. 

running tests I used `rake test` or is there something else as I do see errors on master as well.

**Comment by flavorjones** [comment]
The underlying rakefiles and gemspec have evolved enough that I'm going to close this and start a new PR. I'll tag @headius and @mkristian for review and feedback on it.

**Pull request closed without merging**
