### PR TITLE
fix over-eager namespace pruning when reparenting nodes

### LINKED ISSUE #1332: element in incorrect namespace after adding as a child
```
require 'nokogiri'

doc = Nokogiri::XML('<xml xmlns:a="abc"></xml>')
doc2 = Nokogiri::XML('<more xmlns="abc" />')
doc.root << doc2.root

puts doc
```

I would expect the output to be either

a) it used the outer namespace definition, and moved the element into it
```
<?xml version="1.0"?>
<xml xmlns:a="abc">
  <a:more/>
</xml>
```

or

b) it preserves the namespace that doesn't match on prefix, returning
```
<?xml version="1.0"?>
<xml xmlns:a="abc">
  <more xmlns="abc"/>
</xml>
```

but instead the output is
```
<?xml version="1.0"?>
<xml xmlns:a="abc">
  <more/>
</xml>
```

and more's namespace is no longer "abc".  This seems to be a problem with the `relink_namespace` function, that it removes duplicate namespaces, even if the prefixes don't match (and even if they did, you'd need to make sure the prefix wasn't redeclared between the higher definition and the lower definition)

### PR DESCRIPTION
**Pull request by ccutrer**
fixes #1332

### CODE REVIEW

**Comment by sgringwe** [comment]
I would love to see this pull request merged as it affects us too, any update on this?

**Comment by sgringwe** [comment]
@larskanis is there any update on this? we are still locked into @ccutrer 's version and would love to of course be able to get updates from newer versions

**Comment by larskanis** [comment]
This PR sounds reasonable to me. It doesn't fully align JRuby and MRI implementations, but brings it closer together.

@flavorjones Could you please have a look at this?

**Comment by bradleybeddoes** [comment]
@larskanis @flavorjones any chance of this making it into 1.6.8? I'm also getting tripped up on this one.

**Comment by flavorjones** [comment]
Yes, plan is to include in 1.6.8 final. Spent tonight going through old issues, will spend my next hack night finishing 1.6.8. Thanks for your patience.

**Comment by flavorjones** [comment]
Apologies to just getting to this now -- the second test passes on master, can you help me understand why it's there?

Also, there are two conditionals being added to the `ns` check (both are NULL, or both are equal) and I'd like to make sure they're both being tested.

**Comment by bradleybeddoes** [comment]
What is the process here for assisting on a PR proposed by someone else?. 

I am happy to try and assist resolve these questions but I don't want to impact/take any credit for the good work already done by @ccutrer.

**Comment by bradleybeddoes** [comment]
Further to the above comment if it is helpful in any way I've proposed https://github.com/sparklemotion/nokogiri/pull/1444

**Comment by bradleybeddoes** [comment]
@flavorjones did you have any further thoughts on this PR or #1444 ?

Apologies for being a pest about this, it is just a really important fix for a new project I need to ship asap.

**Comment by flavorjones** [comment]
I merged one of these tests and the fix into master manually and given you credit in the commit log.

I apologize I couldn't find a better way to keep your name on the commits.

Thank you so much!

**Pull request closed without merging**
