### PR TITLE
Remove patch of libxml2 reg. isnan/isinf on musl systems

### PR DESCRIPTION
**Pull request by larskanis**
It is no longer necessary with rake-compiler-dock-1.2.1.

**What problem is this PR intended to solve?**

The nokogiri binary gem for linux wan't usable on musl based systems due to unresolved symbols `__isnan` and `__isinf`. This is described here: https://github.com/rake-compiler/rake-compiler-dock/issues/42

**Have you included adequate test coverage?**

Tests on alpine are already part of the CI.

**Does this change affect the behavior of either the C or the Java implementations?**

C only.

### CODE REVIEW

**Comment by larskanis** [comment]
What a bummer! Now it segfaults on musl-linux: https://github.com/sparklemotion/nokogiri/runs/5582802058?check_suite_focus=true#step:5:669

**Comment by flavorjones** [comment]
Ah, that was built with the docker image from 1.2.0 ... see https://github.com/sparklemotion/nokogiri/runs/5582709245?check_suite_focus=true

Let me update the CI pipeline to use the new image (1.2.1) and see what happens.

**Comment by flavorjones** [comment]
@larskanis Passes with the new docker image! Merging.

**Comment by larskanis** [comment]
Nice! Thank you!

**Pull request merged**
