### PR TITLE
WIP: Cross compile for x86_64-darwin and arm64-darwin per rake-compiler-dock

### PR DESCRIPTION
**Pull request by larskanis**
This requires latest rake-compiler-dock from master branch.

**What problem is this PR intended to solve?**

Fat binary gems for MacOS are currently built on MacOS native. This complicates the build and release cycle. It is desirable to build all binary gems per cross compiler.

Related to #2079

**Have you included adequate test coverage?**

No CI, but I tested the resulting `x86_64-darwin` gem on MacOS-10.14.4 with both the system ruby-2.3.7 (after extending the `required_ruby_version` of nokogiri) and ruby-2.7.2 installed per rvm. The Mac is running on https://github.com/foxlet/macOS-Simple-KVM .

I'm unable to execute the `arm64-darwin` on any computer. I just did some static inspection of the built `nokogiri.bundle` file.

**Does this change affect the behavior of either the C or the Java implementations?**

C only.

### CODE REVIEW

**Comment by flavorjones** [comment]
@larskanis This is exciting! Thanks for doing this work. I'll spend some time tomorrow trying it out, and I'll ask some questions inline.

**Comment by larskanis** [comment]
I played a bit with universal libraries to bundle x86_64+arm64 code into one package, but that didn't work. IMHO these universal builds require a lot of additional work compared to a clear separation of CPU architectures.

**Comment by flavorjones** [comment]
I'm kicking the tires today and everything looks good, including the darwin x86_64 gem. I'd like to ship an rc4 in the next day or so so we can get feedback on the arm64 build in particular in time for a v1.11.0 final release by year's end.

@larskanis Are you planning to release rake-compiler-dock v1.1.0 soon so I can merge this?

**Comment by larskanis** [comment]
> Are you planning to release rake-compiler-dock v1.1.0 soon so I can merge this?

Yes, I'm planning to release rake-compiler-dock-1.1.0 soon after ruby-3.0 and before end of the year.

**Comment by flavorjones** [comment]
I've pushed a few related commits. I'll likely keep rebasing this to master HEAD so that I can cut and test release candidates. Sorry for the inconvenience.

**Comment by larskanis** [comment]
IMHO rake-compiler-dock-1.1.0 is ready to be released. I switched to [manylinux](https://github.com/pypa/manylinux/tree/manylinux2014) for the linux cross builds as sugested [here](https://github.com/rake-compiler/rake-compiler-dock/issues/33). I'm not fully convinced about this change, but I think the advantages outweigh the disadvantages. Is this OK for you?

I would like to add the CrossRuby class of Nokogiri to rake-compiler-dock (in a somewhat more generic way). It helps to build and verify other gems similar to nokogiri. Not in 1.1.0, but in a later release.

**Comment by flavorjones** [comment]
@larskanis Thanks for asking - I think that's fine, I've built those images locally and am trying the builds out tonight.

If you'd like to re-use the CrossRuby class, I'd like to suggest changing the file format to be something more easily parseable (like YAML, for instance) because I end up reading it in a few different places (e.g., where I generate the CI pipelines). Maybe we can open up an issue for future discussion? I'm happy to help.

**Comment by flavorjones** [comment]
I used a rebased version of this branch to ship v1.11.0.rc4 just now, and things look like they're going OK! See https://github.com/sparklemotion/nokogiri/issues/2149#issuecomment-752161818

**Comment by larskanis** [comment]
I released rake-compiler-dock-1.1.0 and all the images some hours ago. I think this PR can be merged now.

**Comment by flavorjones** [comment]
OK, I've rebased onto master and fixed some of my commits; waiting for this to go green and I'll ship it.

**Comment by flavorjones** [comment]
@larskanis it looks like the move to centos may have introduced an issue running on musl-based systems, see [cruby-native-gem-test-32bit #25.1 - Concourse](https://ci.nokogiri.org/teams/nokogiri-core/pipelines/nokogiri-pr/jobs/cruby-native-gem-test-32bit/builds/25.1#L5fc5b11c:212). I need to do a bit more digging to be sure and reproduce locally.

**Comment by larskanis** [comment]
> it looks like the move to centos may have introduced an issue running on musl-based systems

Oh, that's not good. And it reminds me that I should have done this musl test locally before release. It's too late for today, but I can check this tomorrow.

**Comment by flavorjones** [comment]
@larskanis I've pushed an additional commit that makes extconf.rb support a `--prevent-strip` argument so that I could get see what's going on in the debugger.

After running the test suite about a dozen times and examining the stack walkback for each, the crashes are happening while libxml2 is trying to call either `isnan` or `isinf` (from `xpath.c` functions `xmlXPathIsNaN` or `xmlXPathIsInf`).

Looking at the shared object generated in the centos container, we can see these end up being method calls:

```
bash-5.0# nm /usr/local/bundle/gems/nokogiri-1.11.0.rc4-x86_64-linux/lib/nokogiri/3.0/nokogiri.so | egrep "isnan|isinf"
                 U __isinf@@GLIBC_2.2.5
                 U __isnan@@GLIBC_2.2.5
```

but in a shared object generated in a debian-based container, there are no such symbols, undefined or other. I _think_ this is because it's defined as a macro on musl and debian?

I feel like we could work around this if necessary by providing local versions, but I'm curious if you can see an easier way to resolve this issue.

**Comment by flavorjones** [comment]
I've pushed a commit that patches libxml2 to avoid calling `isinf` or `isnan` which will let me ship this release. I'd be happy to figure out a more permanent fix, but let's not block on it. I'll open a rake-compiler-dock issue for this.

**Comment by flavorjones** [comment]
Merged! Thanks again, @larskanis!

**Pull request merged**
