### PR TITLE
Update libxslt and libxml2 config.guess files

### PR DESCRIPTION
**Pull request by hernan-erasmo**
Perhaps this is a more clean solution to fix issues like #1280 where nokogiri fails to build because the libs can't identify the correct architecture, since their config.guess file is outdated.

This PR updates both config.guess files for libxml2 and libxslt to the [latest version](http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD).

### CODE REVIEW

**Comment by larskanis** [comment]
Thanks, @hernan-erasmo !

**Comment by flavorjones** [comment]
@hernan-erasmo Thanks for this. I think I'd like to get this (or your other PR) into 1.6.7, since it seems to be turning into an "installation improvement" release. ;)

**Comment by larskanis** [comment]
@flavorjones Any objections to merge this? The CI failures are unrelated.

**Comment by flavorjones** [comment]
Nope, no objections. Cutting 1.6.7.rc4 today, will pull this in.

**Comment by hernan-erasmo** [comment]
Since the first commits of this PR some updates has been made to the config.guess file [(source here)](http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD)

I figured that since this PR hasn't been merged yet, you might as well merge an updated version of the files.

Cheers!

**Comment by SriramaSharma** [comment]
@flavorjones Can you please confirm if this change has made to the 1.6.7.rc4 or to the main branch ?

**Comment by flavorjones** [comment]
Confirmed the contents of config.guess are what we expect, post-patch.

This isn't optimal, as it's persisting the *difference* between libxml2's current file and the latest from the `config` project, but it's good enough for now. When it breaks (and it will, whenever libxml2/libxslt update their config), we'll likely change this implementation to simply copy in the latest `config.guess` rather than try to patch what's there.

@hernan-erasmo: Have you sent a patch upstream to libxml2/libxslt to update their config.guess? If not, I'd like to ask that you do.

Merged into master now. Will be in 1.6.7.rc4.

**Pull request closed without merging**
