### PR TITLE
Backport Ruby 2.4 support for Windows to 1.7.x

### PR DESCRIPTION
**Pull request by nurse**
for master see #1618

### CODE REVIEW

**Comment by flavorjones** [comment]
Hi @nurse, thank you for this pull request. The next release of Nokogiri is intended to be 1.8.0, which would add Windows Ruby 2.4 support and remove Windows Ruby 2.1 support (which just reached EOL).

I was not planning on backporting Ruby 2.4 into 1.7.x, primarily because that's a lot of rubies to have vendored into the fat binary gem. I'm open to changing my mind, though.

Does anyone else feel strongly that we should cut a 1.7.x release adding Windows Ruby 2.4 support?

**Comment by larskanis** [comment]
IMHO we should release 1.8.0 ASAP - not another 1.7.x. Maybe with a prerelease first, but I wouldn't stick on the 1.7.x branch. I would also offer my help in bringing 1.8.0 out. @flavorjones What are the open tasks?

There are 2 remaining issues targeted to 1.8.0 on [the current milestones list](https://github.com/sparklemotion/nokogiri/milestone/10) (the memory leak and the segfault). Both are present since years, so I wouldn't delay the 1.8.0 release by these two.

Nevertheless I see the urgent need to release a new fat binary gem for Windows, because I released RubyInstaller-2.4 last week. Although it's relatively simple to use the source gem instead, almost everyone stumbles into the issue #1618 first, and that isn't a nice welcome.

**Comment by flavorjones** [comment]
@larskanis thanks for replying. let's give @nurse the opportunity to respond.

Also - @nurse - if you'll kindly rebase onto `v1.7.x`, the concourse-ci check should pass (I've cherry-picked 9d24e8a onto `v1.7.x`).

**Comment by nurse** [comment]
@flavorjones I was OK to wait v1.8.0 (I created https://github.com/sparklemotion/nokogiri/issues/1618) but I wait 3 months. 
If v1.8.0 still requires more weeks, I want to release v1.7.3.

**Comment by flavorjones** [comment]
I commit to releasing 1.8.0 by this weekend. Will leave this open until then.

**Comment by nurse** [comment]
Sure, I wait it.

**Comment by flavorjones** [comment]
Closed, I've shipped 1.8.0 with Windows Ruby 2.4 support instead.

**Pull request closed without merging**
